/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StallsRouteImport } from './routes/stalls'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PresentRouteImport } from './routes/present'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as MyRegistrationRouteImport } from './routes/my-registration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'

const StallsRoute = StallsRouteImport.update({
  id: '/stalls',
  path: '/stalls',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRegistrationRoute = MyRegistrationRouteImport.update({
  id: '/my-registration',
  path: '/my-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-registration': typeof MyRegistrationRoute
  '/payment': typeof PaymentRoute
  '/payments': typeof PaymentsRoute
  '/present': typeof PresentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/seasons': typeof SeasonsRoute
  '/signup': typeof SignupRoute
  '/stalls': typeof StallsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-registration': typeof MyRegistrationRoute
  '/payment': typeof PaymentRoute
  '/payments': typeof PaymentsRoute
  '/present': typeof PresentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/seasons': typeof SeasonsRoute
  '/signup': typeof SignupRoute
  '/stalls': typeof StallsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories': typeof CategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/my-registration': typeof MyRegistrationRoute
  '/payment': typeof PaymentRoute
  '/payments': typeof PaymentsRoute
  '/present': typeof PresentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/seasons': typeof SeasonsRoute
  '/signup': typeof SignupRoute
  '/stalls': typeof StallsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/categories'
    | '/draw'
    | '/gallery'
    | '/login'
    | '/my-registration'
    | '/payment'
    | '/payments'
    | '/present'
    | '/profile'
    | '/register'
    | '/reports'
    | '/seasons'
    | '/signup'
    | '/stalls'
    | '/categories/$categoryId'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/draw'
    | '/gallery'
    | '/login'
    | '/my-registration'
    | '/payment'
    | '/payments'
    | '/present'
    | '/profile'
    | '/register'
    | '/reports'
    | '/seasons'
    | '/signup'
    | '/stalls'
    | '/categories/$categoryId'
    | '/categories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/categories'
    | '/draw'
    | '/gallery'
    | '/login'
    | '/my-registration'
    | '/payment'
    | '/payments'
    | '/present'
    | '/profile'
    | '/register'
    | '/reports'
    | '/seasons'
    | '/signup'
    | '/stalls'
    | '/categories/$categoryId'
    | '/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  DrawRoute: typeof DrawRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MyRegistrationRoute: typeof MyRegistrationRoute
  PaymentRoute: typeof PaymentRoute
  PaymentsRoute: typeof PaymentsRoute
  PresentRoute: typeof PresentRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SeasonsRoute: typeof SeasonsRoute
  SignupRoute: typeof SignupRoute
  StallsRoute: typeof StallsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stalls': {
      id: '/stalls'
      path: '/stalls'
      fullPath: '/stalls'
      preLoaderRoute: typeof StallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-registration': {
      id: '/my-registration'
      path: '/my-registration'
      fullPath: '/my-registration'
      preLoaderRoute: typeof MyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  DrawRoute: DrawRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MyRegistrationRoute: MyRegistrationRoute,
  PaymentRoute: PaymentRoute,
  PaymentsRoute: PaymentsRoute,
  PresentRoute: PresentRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SeasonsRoute: SeasonsRoute,
  SignupRoute: SignupRoute,
  StallsRoute: StallsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
